export const LISTEN_TO_CURRENT_USRER_PROFILE = 'LISTEN_TO_CURRENT_USRER_PROFILE';
export const LISTEN_TO_SELECTED_USRER_PROFILE = 'LISTEN_TO_SELECTED_USRER_PROFILE';
export const LISTEN_TO_USER_PHOTOS = 'LISTEN_TO_USER_PHOTOS';